
<?php
/**
 * Implements hook_theme().
 */
function assignment_theme() {
  return [
    'location_block' => [
      'variables' => [
        'data' => [],
      ],
    ],
  ];
}
/**
 * Implements hook_preprocess_HOOK()
 */
function assignment_preprocess_block(&$variables) {
  if ($variables['plugin_id'] == 'assignment_location_block') {
    $variables['#attached']['library'][] = 'assignment/assignment';
  }
}